### PR TITLE
Updated server.js, Formatted + More Stuff

### PR DESCRIPTION
**Pull request by pushbytes**
Formatted Everything to a cleaner style, added a better "console.log, console.error, console.warn" system using Winston 👍

### CODE REVIEW

**Comment by ghost** [comment]
Also it says SystemOS, forgot to edit that mb lol

(the reason is says SystemOS is because it was from my project
to use the thingy (output) do `npm i winston`

**Comment by 2JJ1** [comment]
In Javascript, it's much more common to use camelcase for naming. https://www.w3schools.com/js/js_conventions.asp

It does look clean with the way you do your imports, but I usually see them done the way I do it, so I'll just stick to that. Really, I wouldn't change up the conventions for just this one page if the rest of the project does it another. I like to be uniform. Even if parts of the project are awkward in convention, at least it goes for consistency. 
That said, if you choose to make other commits, please follow the existing convention. Otherwise, I'd just rewrite it all. No point in rewriting these of course since it'd just be back to how I wrote it.

**Comment by 2JJ1** [comment]
My opinion of using winston is up and down. With using a process manager like PM2, which I'd recommend in production, the effects of winston are mostly replicated. Though I am aware that not 100% of people would be using PM2. I'll think on it

**Comment by ghost** [comment]
Alr

**Pull request closed without merging**
